app_name = "servicios_publicos"
app_title = "Servicios Públicos Colombia"
app_publisher = "Sistema Servicios Públicos"
app_description = "Aplicación para gestión de servicios públicos en Colombia"
app_email = "admin@serviciospublicos.local"
app_license = "GPL-3.0"
app_version = "1.0.0"
